AAFAQ_COLUMNS = [
    "QuestionID",
    "QuestionText",
    "QuestionParticle",
    "QuestionParticleType",
    "QuestionType",
    "List",
    "AnswerType",
    "Intent",
    "CognitiveLevel",
    "Category",
    "ComplexityLevel",
    "Subjectivity",
    "TemporalContext",
    "PurposeContext",
    "AnswerSourceText",
    "Answer",
]

AAFAQ_COMPATIBLE_COLUMNS = [f"AAFAQ_{c}" for c in AAFAQ_COLUMNS]

CASE_STUDY_CORE_COLUMNS = [
    "case_id",
    "question_ar",
    "department_code",
    "department_ar",
    "operational_metric",
    "operational_metric_ar",
    "synthetic_value",
    "unit",
    "risk_status",
    "question_tool",
    "question_tool_type",
    "question_type",
    "list",
    "answer_type",
    "intent",
    "cognitive_level",
    "subjectivity",
    "temporal_context",
    "expected_time_scope",
    "purpose_context",
    "bi_purpose_target",
    "expected_answer_form",
    "reference_answer_ar",
    "direct_answer_without_conditioning_ar",
    "conditioned_answer_ar",
    "answer_form_adherent_without",
    "answer_form_adherent_with",
    "temporal_adherent_without",
    "temporal_adherent_with",
    "purpose_aligned_without",
    "purpose_aligned_with",
    "split",
    "notes",
]

ADHERENCE_COLUMNS = [
    "answer_form_adherent_without",
    "answer_form_adherent_with",
    "temporal_adherent_without",
    "temporal_adherent_with",
    "purpose_aligned_without",
    "purpose_aligned_with",
]

TAXONOMY_COLUMNS = [
    "AAFAQ_QuestionParticle",
    "AAFAQ_QuestionParticleType",
    "AAFAQ_QuestionType",
    "AAFAQ_List",
    "AAFAQ_AnswerType",
    "AAFAQ_Intent",
    "AAFAQ_CognitiveLevel",
    "AAFAQ_Subjectivity",
    "AAFAQ_TemporalContext",
    "AAFAQ_PurposeContext",
]

CLASSIFICATION_TARGET_COLUMNS = [
    "QuestionParticle",
    "QuestionParticleType",
    "QuestionType",
    "List",
    "AnswerType",
    "Intent",
    "CognitiveLevel",
    "Subjectivity",
    "TemporalContext",
    "PurposeContext",
]
